module.exports = {
    accounting: {
        BALANCE: '/main/api/v2/accounting/account2/{currency}',
        BALANCES: '/main/api/v2/accounting/accounts2',
        ACTIVITIES: '/main/api/v2/accounting/activity/{currency}',
        DEBT_INDIDENT: '/main/api/v2/accounting/debt/create/{incidentId}/{currency}/{single}',
        DEBT_PAY: '/main/api/v2/accounting/debt/pay',
        DEPOSIT_ADDRESS: '/main/api/v2/accounting/depositAddresses',
        DEPOSITS: '/main/api/v2/accounting/deposits/{currency}',
        DEPOSIT: '/main/api/v2/accounting/deposits2/{currency}/{id}',
        EXCHANGE_ORDER_TRANSACTIONS: '/main/api/v2/accounting/exchange/{id}/trades',
        HASHPOWER_ORDER_TRANSACTIONS: '/main/api/v2/accounting/hashpower/{id}/transactions',
        MINING_PAYMENTS: '/main/api/v2/accounting/hashpowerEarnings/{currency}',
        TRANSACTION: '/main/api/v2/accounting/transaction/{currency}/{transactionId}',
        TRANSACTIONS: '/main/api/v2/accounting/transactions/{currency}',
        CREATE_WITHDRAWAL: '/main/api/v2/accounting/withdrawal',
        CANCEL_WITHDRAWAL: '/main/api/v2/accounting/withdrawal/{currency}/{id}',
        WITHDRAWAL: '/main/api/v2/accounting/withdrawal2/{currency}/{id}',
        WITHDRAWAL_ADDRESS: '/main/api/v2/accounting/withdrawalAddress/{id}',
        WITHDRAWAL_ADDRESSES: '/main/api/v2/accounting/withdrawalAddresses',
        WITHDRAWALS: '/main/api/v2/accounting/withdrawals/{currency}'
    },
    private_miner: {
        MINING_ADDRESS: '/main/api/v2/mining/miningAddress',
        MINING_ALGO_STATS: '/main/api/v2/mining/algo/stats',
        GROUPS: '/main/api/v2/mining/groups/list',
        RIG_STATS_ALGO: '/main/api/v2/mining/rig/stats/algo',
        RIG_STATS_UNPAID: '/main/api/v2/mining/rig/stats/unpaid',
        RIG_DETAILS: '/main/api/v2/mining/rig2/{rigId}',
        ACTIVE_WORKERS: '/main/api/v2/mining/rigs/activeWorkers',
        PAYOUTS: '/main/api/v2/mining/rigs/payouts',
        MINER_STATS_ALGO: '/main/api/v2/mining/rigs/stats/algo',
        MINER_STATS_UNPAID: '/main/api/v2/mining/rigs/stats/unpaid',
        RIG_ACTION: '/main/api/v2/mining/rigs/status2',
        RIGS: '/main/api/v2/mining/rigs2',
    },
    public: {
        MINING_ALGORITHMS: '/main/api/v2/mining/algorithms',
        MINING_MARKETS: '/main/api/v2/mining/markets',
        CURRENCIES: '/main/api/v2/public/currencies',
        FEE_RULES: '/main/api/v2/public/service/fee/info',
        COUNTRIES: '/api/v2/enum/countries',
        KM_COUNTRIES: '/api/v2/enum/kmCountries',
        PERMISSIONS: '/api/v2/enum/permissions',
        XCH_COUNTRIES: '/api/v2/enum/xchCountries',
        API_FLAGS: '/api/v2/system/flags',
        SERVER_TIME: '/api/v2/time',
    },
    reports: {
        CREATE_REPORT: '/main/api/v2/reports/add',
        DELETE_REPORT: '/main/api/v2/reports/delete/{id}',
        DOWNLOAD_PDF_REPORT: '/main/api/v2/reports/download/pdf/{id}',
        DOWNLOAD_CSV_REPORT: '/main/api/v2/reports/download/{id}',
        REPORTS_LIST_OBJECT: '/main/api/v2/reports/list',
    },
    external_miners: {
        ACTIVE_WORKERS: '/main/api/v2/mining/external/{btcAddress}/rigs/activeWorkers',
        MINER_STATS_ALGO: '/main/api/v2/mining/external/{btcAddress}/rigs/stats/algo',
        MINER_STATS_UNPAID: '/main/api/v2/mining/external/{btcAddress}/rigs/stats/unpaid',
        WITHDRAWALS: '/main/api/v2/mining/external/{btcAddress}/rigs/withdrawals',
        RIG_LIST: '/main/api/v2/mining/external/{btcAddress}/rigs2',
    },
    hashpower_private: {
        MY_ORDERS: '/main/api/v2/hashpower/myOrders',
        CREATE_ORDER: '/main/api/v2/hashpower/order',
        ORDER_DETAILS: '/main/api/v2/hashpower/order/{id}',
        CANCEL_ORDER: '/main/api/v2/hashpower/order/{id}',
        REFILL_ORDER: '/main/api/v2/hashpower/order/{id}/refill',
        ORDER_STATISTICS: '/main/api/v2/hashpower/order/{id}/stats',
        UPDATE_PRICE_AND_LIMIT: '/main/api/v2/hashpower/order/{id}/updatePriceAndLimit',
        ESTIMATE_ORDER_DURATION: '/main/api/v2/hashpower/orders/calculateEstimateDuration',
    },
    hashpower_public: {
        ORDER_BOOK: '/main/api/v2/hashpower/orderBook',
        ORDER_SUMMARIES: '/main/api/v2/hashpower/orders/summaries',
        ORDERS_SUMMARY: '/main/api/v2/hashpower/orders/summary',
        ALGORITHM_HISTORY: '/main/api/v2/public/algo/history',
        BUY_INFO: '/main/api/v2/public/buy/info',
        ORDERS: '/main/api/v2/public/orders',
        SIMPLE_STATUS: '/main/api/v2/public/simplemultialgo/info',
        HOUR_STATISTICS: '/main/api/v2/public/stats/global/24h 24',
        CURRENT_STATISTICS: '/main/api/v2/public/stats/global/current',
    },
    pools: {
        CREATE_OR_EDIT_POOL: '/main/api/v2/pool',
        POOL_DETAILS: '/main/api/v2/pool/{poolId}',
        DELETE_POOL: '/main/api/v2/pool/{poolId}',
        POOL_LIST: '/main/api/v2/pools',
        VERIFY_POOL: '/main/api/v2/pools/verify',
    },
    exchange_private: {
        CANCEL_ALL_ORDERS: '/exchange/api/v2/info/cancelAllOrders',
        FEE_STATUS: '/exchange/api/v2/info/fees/status',
        MY_ORDER: '/exchange/api/v2/info/myOrder',
        MY_ORDERS: '/exchange/api/v2/info/myOrders',
        MY_TRADES: '/exchange/api/v2/info/myTrades',
        TRADES_FOR_ORDER: '/exchange/api/v2/info/orderTrades',
        CREATE_NEW_ORDER: '/exchange/api/v2/order',
        CANCEL_ORDER: '/exchange/api/v2/order',
    },
    exchange_public: {
        CANDLESTICKS: '/exchange/api/v2/info/candlesticks',
        EXCHANGE_STATISTICS: '/exchange/api/v2/info/marketStats',
        CURRENT_PRICES: '/exchange/api/v2/info/prices',
        EXCHANGE_STATUS: '/exchange/api/v2/info/status',
        TRADES: '/exchange/api/v2/info/trades',
        ORDER_BOOK: '/exchange/api/v2/orderbook',
    }
};